# Name of the workflow
name: Vale-Linting

# Events that trigger the workflow
on:
  # Triggers on push or pull request events for the main branch
  push:
    branches: [main]
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# Jobs to be executed
jobs:
  build:
    # Runs on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Steps within the job
    steps:
      - name: Checkout
        # Checks out the repository code
        uses: actions/checkout@v3

      - name: Vale
        # Uses the Vale action for linting
        # uses: errata-ai/vale-action@v1.4.2
        uses: errata-ai/vale-action@reviewdog
        with:
          debug: true
          # styles: |
            # https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            # https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            # https://github.com/errata-ai/Joblint/releases/download/v0.4.1/Joblint.zip
